### ISSUE TITLE
Godot headless build does not import some assets 

### ISSUE THREAD

**Issue by guysoft** [guysoft/EnergySource#3]
Godot headless build does not import some assets
Editor works fine however
List is:
```
Only in src/.import: Tiles074_2K_NormalDX.png-e286d5a4f879c8ad22458444cac82e53.etc2.stex
Only in src/.import: Tiles074_2K_NormalDX.png-e286d5a4f879c8ad22458444cac82e53.s3tc.stex
Only in src/.import: Tiles074_2K_Roughness.png-cf1c7997c0833f652a27ce27e5c0fe34.etc2.stex
Only in src/.import: Tiles074_2K_Roughness.png-cf1c7997c0833f652a27ce27e5c0fe34.s3tc.stex
Only in src/.import: circle_05.png-d7810503b6977db978e171053594cb27.etc2.stex
Only in src/.import: circle_05.png-d7810503b6977db978e171053594cb27.s3tc.stex
Only in src/.import: grid.png-aa6ab1fd1f97e22f02b564754520af6c.etc2.stex
Only in src/.import: grid.png-aa6ab1fd1f97e22f02b564754520af6c.s3tc.stex
```

**Comment by guysoft** [comment]
Trying to reproduce here:
https://github.com/guysoft/godot_import_action_reproduce

**Comment by guysoft** [comment]
reproduce:
https://github.com/guysoft/godot_import_action_reproduce/issues/1

**Comment by rainerweston** [comment]
![image](https://user-images.githubusercontent.com/22193184/145133428-b480ad82-260c-496f-a818-44aa115dcd07.png)

Also this might have something: https://github.com/godotengine/godot/issues/27963

**Comment by guysoft** [comment]
Poated here https://github.com/godotengine/godot/issues/55711

**Comment by guysoft** [comment]
Should be fixed/workaround with this commit: https://github.com/guysoft/EnergySource/commit/7adc5d4dd9d18b606780bae07dee9b5091bdb491

**Comment by guysoft** [comment]
Tested, fixed for now. 
Will need to keep an eye on future textures
