### ISSUE TITLE
Figure out how to load music/level files externally without them being part of the project

### ISSUE THREAD

**Issue by guysoft** [guysoft/EnergySource#7]
Related: https://github.com/guysoft/EnergySource/issues/5

**Comment by merspieler** [comment]
does this mean, I need to build it my self, if I want to have more tracks?

**Comment by rainerweston** [comment]
> does this mean, I need to build it my self, if I want to have more tracks?

No this has actually been resolved over a few commits. Closing this issue.

**Comment by guysoft** [comment]
Will also explain what TempoVR does now:
You extract BeatSaver.com levels in the Levels folder in their own folders,  and they should be detected in the main menu.

This might change later on to the user data folder.
Also we need to add a level.dialog where you pick the difficulty.

**Comment by merspieler** [comment]
Okay, thanks... I've got a test track in... that seems to work.

Is it supposed to work with monado? I've tried that but the sabers only rotated but didn't move.
Also I didn't see any blocks yet... not in the default track nor the one added my self.

I'll try to get it running on my system with steamVR and see if it works there.

If I can help in any way to find those issues please let me know.

**Comment by guysoft** [comment]
Stuff we didnt fix yet but you should be able to get working:
1. Blocks - Make sure the dat file of the level is named ``ExpertPlusStandard.dat``, its set here hardcoded ATM: https://github.com/guysoft/EnergySource/blob/main/src/scripts/GameVariables.gd#L54
2. Never tested monado. I did test on SteamVR using a Vive on linux, that does work.
3. It does work with open XR as much as godot does. It should according to this: https://godotengine.org/article/godot-openxr-support. If you can tell me how to test that with a Vive on Ubuntu I can try. What is your setup?

**Comment by merspieler** [comment]
1. okay, that works with my custom song... just set it to ExpertStandard before cause the track wasn't expert+... pebkac

My setup right now:
Debian Testing and Valve Index
Installed package `monado-service`.
Started monado-service from the terminal then run the prebuild TempoVR binary.
